theme: jekyll-theme-dinky
title: João Paulo
description: Agronomyst/researcher. Interested in climate agriculture, environment, remote sensing, climate change and data science. Also C# (12 years exp) and python dev.
